version: '3.5'
services:
  prometheus:
    image: "prom/prometheus:v2.19.2"
    container_name: "prometheus"
    ports:
      - 9090:9090
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
  grafana:
    image: "grafana/grafana:7.1.0"
    container_name: "grafana"
    ports:
      - 3000:3000
  js-executor:
    image: "js-executor"
    container_name: "jsexec"
    ports:
      - 8080:8080





