{
 "title": "js executor dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "request count  5m rate ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "js_executor:request_count:rate", "legendFormat": " {{method}} {{uri}}" }
   ]
  },
  {
   "title": "5m average map size ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "js_executor:map_size:avg", "legendFormat": "map_size_avg" }
   ]
  },
  {
   "title": "5m average script number in  the map",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "js_executor:script_number:avg", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "script number in the map",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "script_number", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "mean script running time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "running_time_mean", "legendFormat": "mean" }
   ]
  },
  {
   "title": "5m rate of total script running time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "js_executor:total_running_time:rate",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "max script running time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "running_time_seconds_max", "legendFormat": "max" }
   ]
  },
  {
   "title": "min script running time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "running_time_seconds{quantile=\"0.0\"}",
     "legendFormat": "min"
    }
   ]
  }
 ]
}