{
 "title": "js executor dashboard Copy",
 "time": { "from": "2020-09-17T19:34:37.878Z", "to": "2020-09-17T20:09:22.980Z" },
 "panels": [
  {
   "title": "request count  5m",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{uri!=\"/actuator/prometheus\"}[5m])",
     "legendFormat": "{{uri}} {{method}}"
    }
   ]
  },
  {
   "title": "map size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "map_size" }
   ]
  },
  {
   "title": "script running time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(running_time_seconds_count[5m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "running scripts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "running_scripts_number", "legendFormat": "running_scripts_number" }
   ]
  }
 ]
}