server:
  port: 8080

spring:
  mvc:
    async:
      request-timeout: -1

executor:
  thread-count: 8
  lang: "js"

springdoc:
  api-docs:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
