server:
  port: 8080

spring:
  task:
    execution:
      pool:
        core-size: 8
        max-size: 8
        queue-capacity: 200
      thread-name-prefix: "app"
  mvc:
    async:
      request-timeout: -1
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 664648248047-a5gjsnegpd7pbvkcp0o0kd8v29974o55.apps.googleusercontent.com
            client-secret: ZXgvi3q6HSSATx4p7Mv7LoqB


executor:
  lang: "js"
  admin-emails: den98lev@gmail.com

springdoc:
  swagger-ui:
    url: "/openapi.json"
    path: "/swagger-doc"

management:
  endpoints:
    web:
      exposure:
        include: "*"
