server:
  port: 8080

spring:
  task:
    execution:
      pool:
        core-size: 8
        max-size: 8
        queue-capacity: 200
      thread-name-prefix: "app"
  mvc:
    async:
      request-timeout: -1
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8084/auth/realms/blah

executor:
  lang: "js"
  admin-emails: den98lev@gmail.com

springdoc:
  swagger-ui:
    url: "/openapi.json"
    path: "/swagger-doc"

management:
  endpoints:
    web:
      exposure:
        include: "*"
