
POST http://localhost:8080/executor/js/script?blocking=true
Content-Type: application/json

{
  "script" : "var c = 0; while(c < 1000){console.log(c++);}"
}

###

POST http://localhost:8080/executor/js/script?blocking=true
Content-Type: application/json

{
  "script" : "var i = 0; while(i < 10) {console.log('hello ' + i++);}"
}

###

POST http://localhost:8080/executor/js/script?blocking=true
Content-Type: application/json

{
  "script" : "console.log('kjcssbajkcbjhsabvddddddddehfhwvhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhansdbcdbmsdbnd');console.log('kjcssbajkcbjhsabvddddddddehfhwvhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhansdbcdbmsdbnd');"
}

###

GET http://localhost:8080/executor/js/script/b1a8aad8-7e71-4dd3-9d63-6ec187f2103e

###

DELETE http://localhost:8080/executor/js/script/b1a8aad8-7e71-4dd3-9d63-6ec187f2103e

###

POST http://localhost:8080/executor/js/script?blocking=false
Content-Type: application/json

{
  "script" : "var.90"
}